---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-role-binding
  namespace: my-ns
subjects:
  - kind: User
    name: uttam
roleRef:
  kind: Role
  name: cluster-role
  apiGroup: rbac.authorization.k8s.io
