---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-role-binding
  namespace: my-ns
subjects:
  - kind: User
    name: maruti
roleRef:
  kind: Role
  name: pods-reader
  apiGroup: rbac.authorization.k8s.io
...
